/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunningRouteImport } from './routes/running'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PrintResumeRouteImport } from './routes/print-resume'
import { Route as HealthcheckRouteImport } from './routes/healthcheck'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminStravaIndexRouteImport } from './routes/admin/strava/index'
import { Route as AdminPrsIndexRouteImport } from './routes/admin/prs/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminActivitiesIndexRouteImport } from './routes/admin/activities/index'
import { Route as AdminStravaImportRouteImport } from './routes/admin/strava/import'
import { Route as AdminStravaConnectRouteImport } from './routes/admin/strava/connect'
import { Route as AdminStravaCallbackRouteImport } from './routes/admin/strava/callback'
import { Route as AdminPrsNewRouteImport } from './routes/admin/prs/new'
import { Route as AdminAuthCallbackRouteImport } from './routes/admin/auth/callback'
import { Route as AdminPrsIdEditRouteImport } from './routes/admin/prs/$id.edit'

const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintResumeRoute = PrintResumeRouteImport.update({
  id: '/print-resume',
  path: '/print-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcheckRoute = HealthcheckRouteImport.update({
  id: '/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStravaIndexRoute = AdminStravaIndexRouteImport.update({
  id: '/strava/',
  path: '/strava/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPrsIndexRoute = AdminPrsIndexRouteImport.update({
  id: '/prs/',
  path: '/prs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesIndexRoute = AdminActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStravaImportRoute = AdminStravaImportRouteImport.update({
  id: '/strava/import',
  path: '/strava/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStravaConnectRoute = AdminStravaConnectRouteImport.update({
  id: '/strava/connect',
  path: '/strava/connect',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStravaCallbackRoute = AdminStravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPrsNewRoute = AdminPrsNewRouteImport.update({
  id: '/prs/new',
  path: '/prs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthCallbackRoute = AdminAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPrsIdEditRoute = AdminPrsIdEditRouteImport.update({
  id: '/prs/$id/edit',
  path: '/prs/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/healthcheck': typeof HealthcheckRoute
  '/print-resume': typeof PrintResumeRoute
  '/resume': typeof ResumeRoute
  '/running': typeof RunningRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/admin/prs/new': typeof AdminPrsNewRoute
  '/admin/strava/callback': typeof AdminStravaCallbackRoute
  '/admin/strava/connect': typeof AdminStravaConnectRoute
  '/admin/strava/import': typeof AdminStravaImportRoute
  '/admin/activities': typeof AdminActivitiesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/prs': typeof AdminPrsIndexRoute
  '/admin/strava': typeof AdminStravaIndexRoute
  '/admin/prs/$id/edit': typeof AdminPrsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthcheck': typeof HealthcheckRoute
  '/print-resume': typeof PrintResumeRoute
  '/resume': typeof ResumeRoute
  '/running': typeof RunningRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/admin/prs/new': typeof AdminPrsNewRoute
  '/admin/strava/callback': typeof AdminStravaCallbackRoute
  '/admin/strava/connect': typeof AdminStravaConnectRoute
  '/admin/strava/import': typeof AdminStravaImportRoute
  '/admin/activities': typeof AdminActivitiesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/prs': typeof AdminPrsIndexRoute
  '/admin/strava': typeof AdminStravaIndexRoute
  '/admin/prs/$id/edit': typeof AdminPrsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/healthcheck': typeof HealthcheckRoute
  '/print-resume': typeof PrintResumeRoute
  '/resume': typeof ResumeRoute
  '/running': typeof RunningRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/auth/callback': typeof AdminAuthCallbackRoute
  '/admin/prs/new': typeof AdminPrsNewRoute
  '/admin/strava/callback': typeof AdminStravaCallbackRoute
  '/admin/strava/connect': typeof AdminStravaConnectRoute
  '/admin/strava/import': typeof AdminStravaImportRoute
  '/admin/activities/': typeof AdminActivitiesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/prs/': typeof AdminPrsIndexRoute
  '/admin/strava/': typeof AdminStravaIndexRoute
  '/admin/prs/$id/edit': typeof AdminPrsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/healthcheck'
    | '/print-resume'
    | '/resume'
    | '/running'
    | '/admin/login'
    | '/admin/'
    | '/admin/auth/callback'
    | '/admin/prs/new'
    | '/admin/strava/callback'
    | '/admin/strava/connect'
    | '/admin/strava/import'
    | '/admin/activities'
    | '/admin/jobs'
    | '/admin/prs'
    | '/admin/strava'
    | '/admin/prs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthcheck'
    | '/print-resume'
    | '/resume'
    | '/running'
    | '/admin/login'
    | '/admin'
    | '/admin/auth/callback'
    | '/admin/prs/new'
    | '/admin/strava/callback'
    | '/admin/strava/connect'
    | '/admin/strava/import'
    | '/admin/activities'
    | '/admin/jobs'
    | '/admin/prs'
    | '/admin/strava'
    | '/admin/prs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/healthcheck'
    | '/print-resume'
    | '/resume'
    | '/running'
    | '/admin/login'
    | '/admin/'
    | '/admin/auth/callback'
    | '/admin/prs/new'
    | '/admin/strava/callback'
    | '/admin/strava/connect'
    | '/admin/strava/import'
    | '/admin/activities/'
    | '/admin/jobs/'
    | '/admin/prs/'
    | '/admin/strava/'
    | '/admin/prs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HealthcheckRoute: typeof HealthcheckRoute
  PrintResumeRoute: typeof PrintResumeRoute
  ResumeRoute: typeof ResumeRoute
  RunningRoute: typeof RunningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-resume': {
      id: '/print-resume'
      path: '/print-resume'
      fullPath: '/print-resume'
      preLoaderRoute: typeof PrintResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcheck': {
      id: '/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof HealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/strava/': {
      id: '/admin/strava/'
      path: '/strava'
      fullPath: '/admin/strava'
      preLoaderRoute: typeof AdminStravaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prs/': {
      id: '/admin/prs/'
      path: '/prs'
      fullPath: '/admin/prs'
      preLoaderRoute: typeof AdminPrsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/': {
      id: '/admin/activities/'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/strava/import': {
      id: '/admin/strava/import'
      path: '/strava/import'
      fullPath: '/admin/strava/import'
      preLoaderRoute: typeof AdminStravaImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/strava/connect': {
      id: '/admin/strava/connect'
      path: '/strava/connect'
      fullPath: '/admin/strava/connect'
      preLoaderRoute: typeof AdminStravaConnectRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/strava/callback': {
      id: '/admin/strava/callback'
      path: '/strava/callback'
      fullPath: '/admin/strava/callback'
      preLoaderRoute: typeof AdminStravaCallbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prs/new': {
      id: '/admin/prs/new'
      path: '/prs/new'
      fullPath: '/admin/prs/new'
      preLoaderRoute: typeof AdminPrsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auth/callback': {
      id: '/admin/auth/callback'
      path: '/auth/callback'
      fullPath: '/admin/auth/callback'
      preLoaderRoute: typeof AdminAuthCallbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/prs/$id/edit': {
      id: '/admin/prs/$id/edit'
      path: '/prs/$id/edit'
      fullPath: '/admin/prs/$id/edit'
      preLoaderRoute: typeof AdminPrsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuthCallbackRoute: typeof AdminAuthCallbackRoute
  AdminPrsNewRoute: typeof AdminPrsNewRoute
  AdminStravaCallbackRoute: typeof AdminStravaCallbackRoute
  AdminStravaConnectRoute: typeof AdminStravaConnectRoute
  AdminStravaImportRoute: typeof AdminStravaImportRoute
  AdminActivitiesIndexRoute: typeof AdminActivitiesIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminPrsIndexRoute: typeof AdminPrsIndexRoute
  AdminStravaIndexRoute: typeof AdminStravaIndexRoute
  AdminPrsIdEditRoute: typeof AdminPrsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuthCallbackRoute: AdminAuthCallbackRoute,
  AdminPrsNewRoute: AdminPrsNewRoute,
  AdminStravaCallbackRoute: AdminStravaCallbackRoute,
  AdminStravaConnectRoute: AdminStravaConnectRoute,
  AdminStravaImportRoute: AdminStravaImportRoute,
  AdminActivitiesIndexRoute: AdminActivitiesIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminPrsIndexRoute: AdminPrsIndexRoute,
  AdminStravaIndexRoute: AdminStravaIndexRoute,
  AdminPrsIdEditRoute: AdminPrsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HealthcheckRoute: HealthcheckRoute,
  PrintResumeRoute: PrintResumeRoute,
  ResumeRoute: ResumeRoute,
  RunningRoute: RunningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
