# fly.toml app configuration file generated for joshgretz-www on 2024-05-06T14:57:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joshgretz-www'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
