import {GetContainer} from 'injectx';
import type {RunningConfig} from './Types';
import {createDatabase} from 'database';

export * from './Types';
export * from './services';
export {findActivityById} from './query/findActivityById';
export {findActivityByStravaId} from './query/findActivityByStravaId';
export {findFirstActivityByLatLon} from './query/findFirstActivityByLatLon';
export {findPersonalRecordsByUserId} from './query/findPersonalRecordsByUserId';
export {findPersonalRecordById} from './query/findPersonalRecordById';
export {createPersonalRecord} from './command/createPersonalRecord';
export {updatePersonalRecord} from './command/updatePersonalRecord';
export {deletePersonalRecord} from './command/deletePersonalRecord';
export {deleteActivityByStravaId} from './command/deleteActivityByStravaId';
export {searchActivities} from './query/searchActivities';
export {findFutureRacesByUserId} from './query/findFutureRacesByUserId';
export {findFutureRaceById} from './query/findFutureRaceById';
export {createFutureRace} from './command/createFutureRace';
export {updateFutureRace} from './command/updateFutureRace';
export {deleteFutureRace} from './command/deleteFutureRace';
export {findStreakByUserId} from './query/findStreakByUserId';
export {upsertStreak} from './command/upsertStreak';
export {aggregateStreakStats} from './query/aggregateStreakStats';
export {recalculateStreak} from './services/recalculateStreak';
export {findStateStatsByUserId} from './query/findStateStatsByUserId';
export {upsertStateStats} from './command/upsertStateStats';
export {aggregateStatsByState} from './query/aggregateStatsByState';
export {recalculateStateStats} from './services/recalculateStateStats';
export {findFirstMarathonsByState} from './query/findFirstMarathonsByState';
export {US_STATES, STATE_NAME_TO_ABBR, stateNameToAbbr} from './constants/us-states';
export {findDailyStatsByUserIdAndYear} from './query/findDailyStatsByUserIdAndYear';
export {upsertDailyStats} from './command/upsertDailyStats';
export {aggregateDailyStats} from './query/aggregateDailyStats';
export {recalculateDailyStats} from './services/recalculateDailyStats';
export {findActivitiesByDateRange} from './query/findActivitiesByDateRange';

export const setupRunningContainer = ({databaseUrl}: RunningConfig) => {
  GetContainer().Bind(createDatabase(databaseUrl), {name: 'database'});
};
